### ISSUE TITLE
POST /auth/register-restaurant-employee

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#104]
Wydaje mi się że powinno zwracać employeeID, żeby dało się przypisać do danej restauracji

**Comment by linewelder** [comment]
Przecierz zwracamy
https://github.com/Reservant-inc/reservant-backend/blob/2f876a4e5423f1504cb3e114480f830ed94365ed/Api/Controllers/AuthController.cs#L53
