### ISSUE TITLE
Grupa nie usuwa się po usunięciu z niej wszystkich restauracji

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#123]
O ile się nie mylę miało nie być pustych grup

![image](https://github.com/Reservant-inc/reservant-backend/assets/50219282/16e7ac04-59ed-4cb9-90c2-5a9fe63cb1ca)

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Grupa nie usuwa się po usunięciu wszystkich restauracji z niej](https://trello.com/c/cTiwPvl9/118-fix-grupa-nie-usuwa-si%C4%99-po-usuni%C4%99ciu-wszystkich-restauracji-z-niej)

**Comment by linewelder** [comment]
(nie zmergowałem jeszcze deva)
