### ISSUE TITLE
Wyszukiwanie po parametrze

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#130]
Opcjonalny parametr (np get /my-restaurants?name=...) pozwalający na wyszukiwanie elementów w końcówkach get, zwracających listę

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEATURE] Wyszukiwanie w /my-restaurants](https://trello.com/c/n90K3atU/119-feature-wyszukiwanie-w-my-restaurants)
