### ISSUE TITLE
/my-restaurants/:id 500Internal Server Error

### ISSUE THREAD

**Issue by s21148** [Reservant-inc/reservant-backend#131]
Po próbie update'u jakiejkolwiek nowo dodanej restauracji leci 500.
![issue](https://github.com/Reservant-inc/reservant-backend/assets/150839151/4d0527cd-bd0b-4094-a704-dadc63fc7bfb)

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] PUT /my-restaurants/{restaurantId} rzuca 500](https://trello.com/c/NscuyjGS/117-fix-put-my-restaurants-restaurantid-rzuca-500)
