### ISSUE TITLE
DELETE my-restaurant-groups/id

### ISSUE THREAD

**Issue by s24937** [Reservant-inc/reservant-backend#134]
Dla końcówki DELETE my-restaurant-groups/id, chciałam usunąć restaurant Group o id 24, które utworzyłam. 
Po wysłaniu zapytania wyrzuca (przy innych końcówkach np. POST my-restaurant-groups ), że nie ma restauracji o Id 1 (nie powinna się usunąć), grupa o id 24 też się usunęła (tak jak powinna)
<img width="1143" alt="image" src="https://github.com/Reservant-inc/reservant-backend/assets/127143262/a06bba8a-7992-448d-ad33-f9eb88a7ba50">
<img width="997" alt="image" src="https://github.com/Reservant-inc/reservant-backend/assets/127143262/bfc1eddb-0b6c-4a82-b50c-210debba5c69">

**Comment by linewelder** [comment]
a ta restauracja była w tej grupie? jeśli tak, to powinna była się usunąć
