### ISSUE TITLE
[SEED] Events o id 1 stworzony przez JD

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#152]
Czy możemy ustawic aby pierwszy event był stworzony przez JD? Ułatwi to testy

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[SEED] Wydarzenia dla JD](https://trello.com/c/3bPTugEZ/140-seed-wydarzenia-dla-jd)
