### ISSUE TITLE
[FEATURE]: /friends

### ISSUE THREAD

**Issue by KubaBili001** [Reservant-inc/reservant-backend#154]
Prośba o:
- zmiane receiver i sender id na id znajomego
- zmiane receiver i sender name na name znajomego
- zwracanie zdjecia profilowego znajomego

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Przerobić GET /friends](https://trello.com/c/UJSNtaVR/137-fix-przerobi%C4%87-get-friends)
