### ISSUE TITLE
[FEATURE]: odrzucenie zaproszeń

### ISSUE THREAD

**Issue by KubaBili001** [Reservant-inc/reservant-backend#157]
Prośba o końcówkę do odrzucenia zaproszeń

**Comment by Mroxny** [comment]
> Prośba o końcówkę do odrzucenia zaproszeń

Posiadamy już taką końcówkę
"`/friends/{userId}` Delete a friend or a peding friend request (as the sender or the receiver)"

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEATURE] Odrzucenie zaproszeń do znajomych](https://trello.com/c/WyDPPDqI/138-feature-odrzucenie-zaprosze%C5%84-do-znajomych)
