### ISSUE TITLE
[FEATURE]: zmiana osób w wątku 

### ISSUE THREAD

**Issue by KubaBili001** [Reservant-inc/reservant-backend#158]
Prośba o dodanie możliwości usuwania i dodawania osób do wątku

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEATURE] Zarządzanie wątkami](https://trello.com/c/d9gGGVAD/142-feature-zarz%C4%85dzanie-w%C4%85tkami)
