### ISSUE TITLE
[SEED]: JD nie posiada w zainteresowanych żadnych wydarzeń

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#164]
## Najpierw upewnij się czy:
- [x] **__Sprawdziłeś, że nikt nie zgłosił jeszcze takiego błędu na issues__**
- [x] **__Testujesz na świeżo odtworzonej bazie danych__**

## Opisz jakie dane i dla jakiej końcówki potrzebujesz danych
GET `/user/events-interested-in` mógłby zwrócić chociarz jeden element

## Jak to wygląda obecnie
paginacja w GET `/user/events-interested-in` nie posiada elementów

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[SEED] Wydarzenia dla JD](https://trello.com/c/3bPTugEZ/140-seed-wydarzenia-dla-jd)
