### ISSUE TITLE
[SEED]: brak wizyt dla JD

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#165]
## Najpierw upewnij się czy:
- [x] **__Sprawdziłeś, że nikt nie zgłosił jeszcze takiego błędu na issues__**
- [x] **__Testujesz na świeżo odtworzonej bazie danych__**

## Opisz jakie dane i dla jakiej końcówki potrzebujesz danych
Conajmniej jedna wizyta stworzona przez JD i jedna wizyta w której był JD
(`/user/visits` oraz `/user/visits-history`)

## Jak to wygląda obecnie
JD nie tworzył wizyty ani nie był w żadnej

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[SEED] Wydarzenia dla JD](https://trello.com/c/3bPTugEZ/140-seed-wydarzenia-dla-jd)
