### ISSUE TITLE
[BUG]: Końcówka POST /wallet/add-money zwraca inną odpowiedź niż w dokumentacji

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#166]
- [X] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
W dokumentacji końcówka POST: /wallet/add-money powinna zwracać 200 OK a zwraca 204

## Oczekiwane zachowanie
najlepej chyba 204

## Zrzuty ekranu (opcjonalnie)
![image](https://github.com/user-attachments/assets/f511b419-e283-4eb4-8d50-58b83d248c93)

**Comment by linewelder** [comment]
b428bc1de0b16b1c0fc6747c61c783a00e65f7a5
