### ISSUE TITLE
[SEED]: JD nie posiada żadnych konwersacji

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#167]
## Najpierw upewnij się czy:
- [X] **__Sprawdziłeś, że nikt nie zgłosił jeszcze takiego błędu na issues__**
- [X] **__Testujesz na świeżo odtworzonej bazie danych__**

## Opisz jakie dane i dla jakiej końcówki potrzebujesz danych
Końcówka `/user/threads` zwróciła chociaż jedną konwersację

## Jak to wygląda obecnie
Obecnie nie ma żadnych wątków

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[SEED] Dane seedowane dla JD](https://trello.com/c/3bPTugEZ/140-seed-dane-seedowane-dla-jd)
