### ISSUE TITLE
[BUG]: Internal error podczas wysyłania wiadomości do wątku

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#169]
- [X] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Serwer wywala 500 podczas wysyłania wiadomości w nowo utworzonym wątku

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Tworzymy nowy wątek (POST `/threads`)
2. Wysyłamy wiadomość do nowo utworzonego wątku (POST `/threads/1/messages`)
3. Dostajemy `Error: Internal Server Error`

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] POST /threads/{threadId}/messages](https://trello.com/c/x30jr8Ov/141-fix-post-threads-threadid-messages)

**Comment by linewelder** [comment]
759f8dc497b7c12ccdff6d6af5f99f85bf0d74ec
