### ISSUE TITLE
[BUG]: Literówka w /restaurants/{restaurantId}/deliveries

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#171]
- [X] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
końcówka zwraca obiekt z `delieryId` zamiast `deliveryId` </br>
![image](https://github.com/user-attachments/assets/7e278067-bf2d-44fe-982a-a9bbb1a7ec19)

**Comment by linewelder** [comment]
57e6a51daae84f82f637de8c333498948472e6f5
