### ISSUE TITLE
[BUG]: DELETE /my-restaurant-groups/{groupId} zwraca internal error

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#172]
- [X] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Usunięcie grupy za każdym razem zwraca internal error

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Najlepiej utworzyć najpierw jakąś grupę (POST /my-restaurant-groups)
2. zapamiętujemy id grupy
3. podajemy id grupy podczas usuwania

**Comment by linewelder** [comment]
Problem jest związany z usunięciem restauracji (#203), bo przy usuwaniu grupy usuwają się wszystkie restauracje w niej
