### ISSUE TITLE
[BUG]: GET /restaurants/{restaurantId}/deliveries zwraca internal error

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#173]
- [X] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Świeżo po zresetowaniu bazy danych końcówka zwraca internal error

## Zrzuty ekranu (opcjonalnie)
![image](https://github.com/user-attachments/assets/84f5235d-ad86-4b53-940c-471b2e039c92)

**Comment by linewelder** [comment]
9f202c693ac081a69520e05ab40d47fd34fe5146
