### ISSUE TITLE
[SEED]: John Doe's nie posiada zamówień

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#174]
## Najpierw upewnij się czy:
- [X] **__Sprawdziłeś, że nikt nie zgłosił jeszcze takiego błędu na issues__**
- [X] **__Testujesz na świeżo odtworzonej bazie danych__**

## Opisz jakie dane i dla jakiej końcówki potrzebujesz danych
potrzebuje żeby `/restaurants/1/orders` zwracało chociaż jeden item

**Comment by linewelder** [comment]
Są trzy zamówienia, ale są zakończone (opcja `returnFinished`):
```json
{
  "orderId": 1,
  "visitId": 1,
  "date": "2024-01-01T17:00:00",
  "note": null,
  "cost": 8,
  "status": "Taken"
},
{
  "orderId": 2,
  "visitId": 2,
  "date": "2024-01-04T18:00:00",
  "note": null,
  "cost": 39,
  "status": "Cancelled"
},
{
  "orderId": 3,
  "visitId": 3,
  "date": "2024-01-05T18:00:00",
  "note": null,
  "cost": 84,
  "status": "Taken"
}
```

Jeśli chodzi o bieżące zamówienia, to końcówka `POST /debug/add-future-visit` dodaje wizytę w przyszłości z zamówieniem

**Comment by linewelder** [comment]
@Mroxny czy to nadal jest problem?

**Comment by Mroxny** [comment]
> @Mroxny czy to nadal jest problem?

Tak, przed chwilą sprawdziłem

**Comment by Mroxny** [comment]
A, nie przepraszam. NIe zauważyłem twojej odpowiedzi

> Są trzy zamówienia, ale są zakończone (opcja `returnFinished`):
> 
> ```json
> {
>   "orderId": 1,
>   "visitId": 1,
>   "date": "2024-01-01T17:00:00",
>   "note": null,
>   "cost": 8,
>   "status": "Taken"
> },
> {
>   "orderId": 2,
>   "visitId": 2,
>   "date": "2024-01-04T18:00:00",
>   "note": null,
>   "cost": 39,
>   "status": "Cancelled"
> },
> {
>   "orderId": 3,
>   "visitId": 3,
>   "date": "2024-01-05T18:00:00",
>   "note": null,
>   "cost": 84,
>   "status": "Taken"
> }
> ```
> 
> Jeśli chodzi o bieżące zamówienia, to końcówka `POST /debug/add-future-visit` dodaje wizytę w przyszłości z zamówieniem

**Comment by Mroxny** [comment]
już sprawdzam

**Comment by Mroxny** [comment]
Dobra, jest ok, `returnFinished` się nada
