### ISSUE TITLE
[BUG]: PUT/user "firstName" i "lastName"

### ISSUE THREAD

**Issue by s24937** [Reservant-inc/reservant-backend#181]
## Opisz błąd
dla końcówki PUT/user w polach firstName i lastName można wpisać liczby i znaki specjalne

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Przejdź do Swaggera
2. Kliknij na PUT/user
3. Ustaw pola firstName i lastName dodając znaki specjalne i liczby
4. Wyślij

## Oczekiwane zachowanie
W polach firstName I lastName nie powinno być dozwolone wstawianie znaków specjalnych czy liczb 

<img width="1052" alt="Zrzut ekranu 2024-08-18 o 11 18 49" src="https://github.com/user-attachments/assets/530853e2-32c0-4a63-a6e7-3c8f911d2522">
<img width="1056" alt="Zrzut ekranu 2024-08-18 o 11 19 28" src="https://github.com/user-attachments/assets/a3290fed-94fc-4a84-88a3-8654948fc65b">

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Lepsza walidacja nazw i imion](https://trello.com/c/QmaMoruh/130-fix-lepsza-walidacja-nazw-i-imion)
