### ISSUE TITLE
[FEATURE]: GET /reviews/{reviewId}

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#193]
W mobilce potrzebujemy końcówki która pozwoli pobrać konkretne review używając id

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEATURE] GET /reviews/{reviewId}](https://trello.com/c/IBoiQ1cY/151-feature-get-reviews-reviewid)
