### ISSUE TITLE
[BUG]: GET /deliveries/{deliveryId} ma złą nazwę atrybutu Id

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#194]
- [x] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Zamiast deliveryId jest id

## Zrzuty ekranu (opcjonalnie)
![image](https://github.com/user-attachments/assets/c3e01cfd-a2f3-48f1-8d3f-f91946e10e4e)

**Comment by linewelder** [comment]
4741d982ae226b71777a0d1cfdc444f7cdd94434
