### ISSUE TITLE
[BUG]: POST /auth/register-customer nie waliduje numeru telefonu

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#196]
- [ ] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Jasny i zwięzły opis błędu.
"12345abc" jest uznawane jako poprawny numer telefonu

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Przejdź do „...
2. Kliknij na „....
3. Przewiń w dół do „....
4. Zobacz błąd

## Oczekiwane zachowanie
Jasny i zwięzły opis oczekiwanego zachowania.

## Zrzuty ekranu (opcjonalnie)
Jeśli dotyczy, dodaj zrzuty ekranu, które pomogą wyjaśnić problem.
![obraz](https://github.com/user-attachments/assets/29df34cd-e3af-4636-b1f1-6a617c02ad67)

## Dodatkowy kontekst (opcjonalnie)
Dodaj tutaj wszelkie inne informacje dotyczące problemu.

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Brakująca walidacja](https://trello.com/c/mmrvQ20e/150-fix-brakuj%C4%85ca-walidacja)

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Brakująca walidacja przy rejestracji](https://trello.com/c/3kFa4wlv/156-fix-brakuj%C4%85ca-walidacja-przy-rejestracji)
