### ISSUE TITLE
[BUG]: Przy rejestracji data urodzenia może być w przyszłości

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#197]
## Opisz błąd
Można podać przyszłą datę jako datę urodzenia
- [x] POST /auth/register-restaurant-employee
- [x] POST /auth/register-customer

I być może również:
- [x] PUT /user
- [x] PUT /users/{employeeId}

## Zrzuty ekranu (opcjonalnie)
![obraz](https://github.com/user-attachments/assets/b7e969b0-c2ce-4655-b400-78b5775e24e7)

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Brakująca walidacja](https://trello.com/c/mmrvQ20e/150-fix-brakuj%C4%85ca-walidacja)

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Brakująca walidacja przy rejestracji](https://trello.com/c/3kFa4wlv/156-fix-brakuj%C4%85ca-walidacja-przy-rejestracji)
