### ISSUE TITLE
[BUG]: POST /auth/register-restaurant-employee można podać przyszłą datę urodzenia

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#198]
- [ ] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Jasny i zwięzły opis błędu.
Pozwala na wpisanie daty z przyszłości jak daty urodzenia

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Przejdź do „...
2. Kliknij na „....
3. Przewiń w dół do „....
4. Zobacz błąd

## Oczekiwane zachowanie
Jasny i zwięzły opis oczekiwanego zachowania.

## Zrzuty ekranu (opcjonalnie)
Jeśli dotyczy, dodaj zrzuty ekranu, które pomogą wyjaśnić problem.
![obraz](https://github.com/user-attachments/assets/08fd966b-10de-403a-a831-51d89273a5fe)

## Dodatkowy kontekst (opcjonalnie)
Dodaj tutaj wszelkie inne informacje dotyczące problemu.

**Comment by linewelder** [comment]
Złączmy ten issue z poprzednim
