### ISSUE TITLE
[BUG]: POST /my-restaurants brak walidacji sumy kontrolnej NIP

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#199]
- [ ] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Jasny i zwięzły opis błędu.
NIP z niepoprawną sumą kontrolną zwracany jest jako prawdziwy

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Przejdź do „...
2. Kliknij na „....
3. Przewiń w dół do „....
4. Zobacz błąd

## Oczekiwane zachowanie
Jasny i zwięzły opis oczekiwanego zachowania.

## Zrzuty ekranu (opcjonalnie)
Jeśli dotyczy, dodaj zrzuty ekranu, które pomogą wyjaśnić problem.
![obraz](https://github.com/user-attachments/assets/c6b95996-db8d-4d43-af49-0bb4a18a91ad)
![obraz](https://github.com/user-attachments/assets/bf9a7256-46d2-4cb5-870c-247bca405e0e)

## Dodatkowy kontekst (opcjonalnie)
Dodaj tutaj wszelkie inne informacje dotyczące problemu.

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Brakująca walidacja](https://trello.com/c/mmrvQ20e/150-fix-brakuj%C4%85ca-walidacja)
