### ISSUE TITLE
[BUG]: POST /my-restaurants/validate-first-step walidacja adresu

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#204]
- [ ] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Jasny i zwięzły opis błędu.
"#@$%^&**(gsegsegh" jest uznawane za poprawny adres

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Przejdź do „...
2. Kliknij na „....
3. Przewiń w dół do „....
4. Zobacz błąd

## Oczekiwane zachowanie
Jasny i zwięzły opis oczekiwanego zachowania.

## Zrzuty ekranu (opcjonalnie)
Jeśli dotyczy, dodaj zrzuty ekranu, które pomogą wyjaśnić problem.
![obraz](https://github.com/user-attachments/assets/d69c386d-6843-4c18-8b4c-7518dddfb665)

## Dodatkowy kontekst (opcjonalnie)
Dodaj tutaj wszelkie inne informacje dotyczące problemu.

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Brakująca walidacja restauracji](https://trello.com/c/mmrvQ20e/150-fix-brakuj%C4%85ca-walidacja-restauracji)
