### ISSUE TITLE
[BUG]: POST /my-restaurants/validate-first-step nie waliduje nazwy miasta

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#205]
- [ ] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Jasny i zwięzły opis błędu.
"KRAK0w" jest uznawane za poprawne miasto

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Przejdź do „...
2. Kliknij na „....
3. Przewiń w dół do „....
4. Zobacz błąd

## Oczekiwane zachowanie
Jasny i zwięzły opis oczekiwanego zachowania.

## Zrzuty ekranu (opcjonalnie)
Jeśli dotyczy, dodaj zrzuty ekranu, które pomogą wyjaśnić problem.
![obraz](https://github.com/user-attachments/assets/ce4796bc-25c9-4446-a3da-706c271ad18f)

## Dodatkowy kontekst (opcjonalnie)
Dodaj tutaj wszelkie inne informacje dotyczące problemu.

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Brakująca walidacja](https://trello.com/c/mmrvQ20e/150-fix-brakuj%C4%85ca-walidacja)

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Brakująca walidacja restauracji](https://trello.com/c/mmrvQ20e/150-fix-brakuj%C4%85ca-walidacja-restauracji)
