### ISSUE TITLE
[BUG]: POST /menus dataOd późniejsza niż dataDo

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#208]
## Opisz błąd
- [x] Końcówka pozwala na datę zakończenia menu na wcześniejszą niż rozpoczęcia.
- [x] dateUntil w ogóle nie powinno pozwolić na datę w przeszłości
- [x] To samo tyczy się PUT

## Zrzuty ekranu (opcjonalnie)
![obraz](https://github.com/user-attachments/assets/41eda6c5-61bc-4d95-bd4b-8a4569cae811)

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Brakująca walidacja](https://trello.com/c/mmrvQ20e/150-fix-brakuj%C4%85ca-walidacja)

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Brakująca walidacja przy rejestracji](https://trello.com/c/3kFa4wlv/156-fix-brakuj%C4%85ca-walidacja-przy-rejestracji)
