### ISSUE TITLE
[BUG]: POST /menu-items działa dla restauracji innego właściciela

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#210]
- [ ] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Jasny i zwięzły opis błędu.
Końcówka pozwala jednemu właścicielowi dodać menuItem do restauracji innego właściciela.

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Przejdź do „...
2. Kliknij na „....
3. Przewiń w dół do „....
4. Zobacz błąd

## Oczekiwane zachowanie
Jasny i zwięzły opis oczekiwanego zachowania.

## Zrzuty ekranu (opcjonalnie)
Jeśli dotyczy, dodaj zrzuty ekranu, które pomogą wyjaśnić problem.

## Dodatkowy kontekst (opcjonalnie)
Dodaj tutaj wszelkie inne informacje dotyczące problemu.

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Błędy sprawdzenia uprawnień](https://trello.com/c/8hW6Yd3k/153-fix-b%C5%82%C4%99dy-sprawdzenia-uprawnie%C5%84)
