### ISSUE TITLE
[BUG]: PUT /menu-items/:id nazwa

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#211]
- [ ] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Jasny i zwięzły opis błędu.
"@$$$$$$$$NHJKGGHNUI" jest uznawane za poprawną nazwę
Generalnie takie nazwy przechodzą w każdej końcówce może da się jakiś uniwersalny sposób na to znaleźć

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Przejdź do „...
2. Kliknij na „....
3. Przewiń w dół do „....
4. Zobacz błąd

## Oczekiwane zachowanie
Jasny i zwięzły opis oczekiwanego zachowania.

## Zrzuty ekranu (opcjonalnie)
Jeśli dotyczy, dodaj zrzuty ekranu, które pomogą wyjaśnić problem.

## Dodatkowy kontekst (opcjonalnie)
Dodaj tutaj wszelkie inne informacje dotyczące problemu.

**Comment by linewelder** [comment]
Moim zdaniem nie jest to problemem, jeśli właściciel chce użyć znaków specjalnych w nazwie produktu, np. 'H@CKER BURG3R' lub coś podobnego
