### ISSUE TITLE
[BUG]: POST /ingredients  ujemene amountused

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#213]
- [ ] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Jasny i zwięzły opis błędu.
Można ustawić ilość użytego składnika jako ujemną

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Przejdź do „...
2. Kliknij na „....
3. Przewiń w dół do „....
4. Zobacz błąd

## Oczekiwane zachowanie
Jasny i zwięzły opis oczekiwanego zachowania.

## Zrzuty ekranu (opcjonalnie)
Jeśli dotyczy, dodaj zrzuty ekranu, które pomogą wyjaśnić problem.
![obraz](https://github.com/user-attachments/assets/c2ad048b-9287-4554-8cdd-167fa86adf71)

## Dodatkowy kontekst (opcjonalnie)
Dodaj tutaj wszelkie inne informacje dotyczące problemu.

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Brakująca walidacja](https://trello.com/c/mmrvQ20e/150-fix-brakuj%C4%85ca-walidacja)

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Brakująca walidacja](https://trello.com/c/mmrvQ20e/150-fix-brakuj%C4%85ca-walidacja)

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Brakująca walidacja przy rejestracji](https://trello.com/c/3kFa4wlv/156-fix-brakuj%C4%85ca-walidacja-przy-rejestracji)
