### ISSUE TITLE
[BUG]: Pracownik zaplecza nie potrafi użyć PUT /ingredients/{ingredientId}

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#214]
Jeśli jeden właściciel próbuje edytować składnik drugiego to wyświetla się komunikat:
![obraz](https://github.com/user-attachments/assets/8482d36a-2d24-441c-9e00-8ee21c7d131c)

ale kiedy pracownik danej restauracji próbuje edytować ten składnik to dostaje 403

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Błędy sprawdzenia uprawnień](https://trello.com/c/8hW6Yd3k/153-fix-b%C5%82%C4%99dy-sprawdzenia-uprawnie%C5%84)
