### ISSUE TITLE
[BUG]: DELETE /menus/{menuId}/items rzuca 500

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#215]
- [ ] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Kiedy próbujemy usunąć MenuItem z Menu które nie należy do nas wyrzuca 500.

Jednak czasami tylko wyrzuca 500, aktualnie menuId = 62, menuItemId = 63, użytkownik = PA

## Zrzuty ekranu (opcjonalnie)
![obraz](https://github.com/user-attachments/assets/c0a88035-c0c3-470a-9e26-6294cb7a6de7)

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Niektóre końcówki](https://trello.com/c/rHjsWYBl/152-fix-niekt%C3%B3re-ko%C5%84c%C3%B3wki)

**Comment by Bambi54** [comment]
![image](https://github.com/user-attachments/assets/120bfc8a-3dd3-4f5a-86a1-ab4eca40bcbe)
