### ISSUE TITLE
[BUG]: PUT /my-restaurant-groups/{groupId} rzuca 500

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#216]
- [ ] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Jasny i zwięzły opis błędu.
końcówka rzuca 500 dla poprawnych danych

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Przejdź do „...
2. Kliknij na „....
3. Przewiń w dół do „....
4. Zobacz błąd

## Oczekiwane zachowanie
Jasny i zwięzły opis oczekiwanego zachowania.

## Zrzuty ekranu (opcjonalnie)
Jeśli dotyczy, dodaj zrzuty ekranu, które pomogą wyjaśnić problem.
![obraz](https://github.com/user-attachments/assets/bd1dcd37-3a59-4fb1-b524-c9d6f46c4bab)

## Dodatkowy kontekst (opcjonalnie)
Dodaj tutaj wszelkie inne informacje dotyczące problemu.

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Niektóre końcówki](https://trello.com/c/rHjsWYBl/152-fix-niekt%C3%B3re-ko%C5%84c%C3%B3wki)
