### ISSUE TITLE
[BUG]: DELETE /my-restaurant-groups/{groupId} 500

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#217]
- [ ] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Jasny i zwięzły opis błędu.
Wyrzuca 500 kiedy próbujemy usunąć grupę która nie jest pusta

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Przejdź do „...
2. Kliknij na „....
3. Przewiń w dół do „....
4. Zobacz błąd

## Oczekiwane zachowanie
Jasny i zwięzły opis oczekiwanego zachowania.

## Zrzuty ekranu (opcjonalnie)
Jeśli dotyczy, dodaj zrzuty ekranu, które pomogą wyjaśnić problem.
![obraz](https://github.com/user-attachments/assets/bb293bca-9523-498a-87d4-f2875f3b33b5)

## Dodatkowy kontekst (opcjonalnie)
Dodaj tutaj wszelkie inne informacje dotyczące problemu.

**Comment by linewelder** [comment]
Duplikat #172
