### ISSUE TITLE
[BUG]: PUT /events/{eventId} nie sprawdza, czy mustJoinUntil nie jest w przeszłości

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#218]
- [ ] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
Jasny i zwięzły opis błędu.
mustJoinUntil i time można edytować na datę w przeszłości, jeżeli mustJoinUntil > time ale i tak raczej powinniśmy weryfikować czy to nie jest w przeszłości

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Przejdź do „...
2. Kliknij na „....
3. Przewiń w dół do „....
4. Zobacz błąd

## Oczekiwane zachowanie
Jasny i zwięzły opis oczekiwanego zachowania.

## Zrzuty ekranu (opcjonalnie)
Jeśli dotyczy, dodaj zrzuty ekranu, które pomogą wyjaśnić problem.
![obraz](https://github.com/user-attachments/assets/e044eabc-8211-4ccf-940b-255bdb358de8)

## Dodatkowy kontekst (opcjonalnie)
Dodaj tutaj wszelkie inne informacje dotyczące problemu.

**Comment by linewelder** [comment]
PROPOZYCJA: W końcówce trzeba sprawdzać, czy podajemy nową datę (inną od tej co była już w bazie) i wtedy walidować, czy nie jest w przeszłości

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Brakująca walidacja](https://trello.com/c/mmrvQ20e/150-fix-brakuj%C4%85ca-walidacja)

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Brakująca walidacja przy rejestracji](https://trello.com/c/3kFa4wlv/156-fix-brakuj%C4%85ca-walidacja-przy-rejestracji)
