### ISSUE TITLE
[BUG]: /notifications/bubbles jest POST a powninien być GET

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#229]
- [x] **__Sprawdziłem i nikt nie zgłosił jeszcze takiego błędu na issues__**

## Opisz błąd
powinien być GET `/notifications/bubbles` zamiast POST

![Zrzut ekranu 2024-09-13 171232](https://github.com/user-attachments/assets/4c6569be-aa1e-47d8-b669-55112d5cb0d4)

**Comment by linewelder** [comment]
48fc
