### ISSUE TITLE
[FEATURE]: GET /check-friendship-status

### ISSUE THREAD

**Issue by skrapi2011** [Reservant-inc/reservant-backend#231]
## Czy prośba o funkcję jest związana z problemem? Opisz go
Problem wynika z tego, że na Mobilce chcemy sprawdzić podczas odwiedzania czyjegoś profilu, czy jest on naszym znajomym. Bez tej końcówki, potrzebujemy fetchować wszystkich znajomych a następnie filtrować listę, co jest uciążliwe.

## Opisz rozwiązanie, którego oczekujesz
Przydałaby się końcówka w stylu "GET /check-friendship-status" która: 
+ Albo zwracałaby Boolean isFriend (czy jest znajomym czy nie)
+ Albo zwracałaby Status znajomości (jeżeli są inne stany)

## Opisz alternatywy, które rozważałeś (opcjonalnie)
J.W

## Dodatkowy kontekst (opcjonalnie)
J.W

**Comment by linewelder** [comment]
Ale przecież końcówka `GET /users/{userId}`, która została zmieniona na potrzeby wyświetlenia profili zwraca pole `friendStatus`
