### ISSUE TITLE
[SEED]: Wiekszość restauracji nie ma zdjęć w galerii.

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#232]
## Najpierw upewnij się czy:
- [x] **__Sprawdziłeś, że nikt nie zgłosił jeszcze takiego błędu na issues__**
- [X] **__Testujesz na świeżo odtworzonej bazie danych__**

## Opisz jakie dane i dla jakiej końcówki potrzebujesz danych
Warto żeby restauracje miały galerie zdjęć składające się conajlniej z 5 zdjęć (ofc może to być ten sam zestaw zdjęć). Można zostawić jedną restaurację która wlg nie ma zdjęc ale reszta niech ma

**Comment by linewelder** [comment]
Ale wszystkie restauracje oprócz dwóch już mają zdjęcia w galerii:
| ID | Nazwa | Liczba Zdjęć |
| :--- | :--- | :--- |
| 1 | John Doe's | 1 |
| 2 | John Doe's 2 | 0 |
| 3 | Kowalski's | 0 |
| 4 | Anon's | 11 |
| 5 | Witcher's | 10 |
| 6 | Dune's spices | 9 |
| 7 | Heisenberg's | 7 |
