### ISSUE TITLE
[FEATURE] zdjęcie jako atrybut opcjonalny przy tworzeniu menu

### ISSUE THREAD

**Issue by JaroslawGawrych** [Reservant-inc/reservant-backend#249]
jak w tytule poproszę.

**Comment by JaroslawGawrych** [comment]
w aplikacji na froncie nie będzie zdjęcia menu

**Comment by JaroslawGawrych** [comment]
i w put też /menus/{menuId}

**Comment by JaroslawGawrych** [comment]
I jeszcze put dla /menus/{menuId}/items

**Comment by JaroslawGawrych** [comment]
jednak ten put dla /menus/{menuId}/items jest potrzebny.

**Comment by linewelder** [comment]
na spotkaniu doszliśmy do wniosku, że po prostu usuniemy ten atrybut

**Comment by JaroslawGawrych** [comment]
bardzo G, to jeszcze tylko ten put /menus/{menuId}/items pliska

**Comment by linewelder** [comment]
spojrze spojrze

**Comment by JaroslawGawrych** [comment]
co z tym /menus/{menuId}/items

**Comment by JaroslawGawrych** [comment]
bo w put, który jest nie przyjmuje ID menu itemów, a osobnej końcówki nie ma
więc tak na prawdę nie można edytować przypisania menu itemów do menu
![obraz](https://github.com/user-attachments/assets/9b509fef-1228-41c1-ad37-1343d3903503)
