### ISSUE TITLE
[FEATURE] /auth/refresh-token

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#25]
Potrzebujemy końcówki, która przedłuża żywotność wysłanego tokenu. 
Fajnie jakby końcówka przyjmowała token klienta i zwracała 200 jeśli wszystko w porzątku. Ew końcówka może zwracać nowy token z nową żywotnością

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Końcówka do wznawiania tokena](https://trello.com/c/St15xe1n/42-ko%C5%84c%C3%B3wka-do-wznawiania-tokena)
