### ISSUE TITLE
[BUG] POST `/debug/send-test-notification` zwraca internal error

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#255]
## Opisz błąd
Wywala błąd podczas wywołania  `/debug/send-test-notification`
Przypuszczam że serwer nie sprawdza czy token (jeżeli juz jest) jest poprawny. 

W logach możemy znaleźć:

> An unhandled exception has occurred while executing the request.
> FirebaseAdmin.Messaging.FirebaseMessagingException: The registration token is not a valid FCM registration token
>    at FirebaseAdmin.Util.ErrorHandlingHttpClient`1.SendAndReadAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at FirebaseAdmin.Util.ErrorHandlingHttpClient`1.SendAndDeserializeAsync[TResult](HttpRequestMessage request, CancellationToken cancellationToken)
>    at FirebaseAdmin.Messaging.FirebaseMessagingClient.SendAsync(Message message, Boolean dryRun, CancellationToken cancellationToken)
>    at FirebaseAdmin.Messaging.FirebaseMessaging.SendAsync(Message message, Boolean dryRun, CancellationToken cancellationToken)
>    at FirebaseAdmin.Messaging.FirebaseMessaging.SendAsync(Message message, Boolean dryRun)
>    at FirebaseAdmin.Messaging.FirebaseMessaging.SendAsync(Message message)
>    at Reservant.Api.Push.FirebaseService.SendNotification(Notification notification) in /src/Api/Push/FirebaseService.cs:line 42
>    at Reservant.Api.Services.NotificationService.NotifyUser(Guid targetUserId, NotificationDetails details, String photoFileName) in /src/Api/Services/NotificationService.cs:line 159
>    at Reservant.Api.Services.NotificationService.NotifyNewFriendRequest(Guid senderId, Guid receiverId) in /src/Api/Services/NotificationService.cs:line 198
>    at Reservant.Api.Controllers.DebugController.SendTestNotification(NotificationService service) in /src/Api/Controllers/DebugController.cs:line 49
>    at lambda_method4496(Closure, Object)

Screen:
 ![image](https://github.com/user-attachments/assets/7c564635-2caa-45ba-be7e-44111d882fd6)

**Comment by linewelder** [comment]
logi FTW :fire: :fire: :fire:
