### ISSUE TITLE
[SEED] Proszę o zaseedowanie menu, menu itemów, składników

### ISSUE THREAD

**Issue by JaroslawGawrych** [Reservant-inc/reservant-backend#265]
z uwzględnieniem poprawności zaseedowanych danych (jeśli coś nie przejdzie jako request, to żeby nie było jako zaseedowane w ten sposób)

**Comment by linewelder** [comment]
chcesz żeby było tego więcej? bo już mamy

**Comment by JaroslawGawrych** [comment]
no więcej menu itemów.. zarazie są chyba 3 na restauracje.. troche mało, szczególnie jak testujemy usuwanie
menu też dobrze, żeby ze 4-5 były.. +więcej składników... to wszystko też pomoże sprawdzić jak wygląda aplikacja przy realnej ilości danych (czy się scrolle np nie rozjeżdżaj albo czy menu wyświetlane w różnych miejscach przy dużej ilości danych nie wygląda chaotycznie)
