### ISSUE TITLE
Brak PUT oraz DELETE dla /my-restaurants

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#27]
Kuchnia nie daje mozliwości modyfikowania restauracji

**Comment by linewelder** [comment]
nie mam kartki dla puta :(

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PUT /my-restaurants/{id:int}](https://trello.com/c/cifqiGj4/49-put-my-restaurants-idint)

**Comment by linewelder** [comment]
była na innej liście jednak

**Comment by skrapi2011** [comment]
https://github.com/Reservant-inc/reservant-backend/pull/33
