### ISSUE TITLE
[BUG] GET `/restaurants` zwraca internal error

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#273]
## Opisz błąd

> An unhandled exception has occurred while executing the request.
> System.InvalidOperationException: A tracking query is attempting to project an owned entity without a corresponding owner in its result, but owned entities cannot be tracked without their owner. Either include the owner entity in the result or make the query non-tracking using 'AsNoTracking'.
>    at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.EntityMaterializerInjectingExpressionVisitor.Inject(Expression expression)
>    at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.VisitExtension(Expression extensionExpression)
>    at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ProcessShaper(Expression shaperExpression, RelationalCommandCache& relationalCommandCache, IReadOnlyList`1& readerColumns, LambdaExpression& relatedDataLoaders, Int32& collectionId)
>    at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.VisitExtension(Expression extensionExpression)
>    at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
>    at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
>    at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
>    at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)

![image](https://github.com/user-attachments/assets/31b438e6-8480-4c07-8a4a-187c788425f3)

**Comment by linewelder** [comment]
hm, ciekawe
