### ISSUE TITLE
[BUG] PUT menu-items/:id

### ISSUE THREAD

**Issue by Dzwiedzi** [Reservant-inc/reservant-backend#288]
## Opisz błąd
to jest uznawane za poprawną nazwę

## Zrzuty ekranu (opcjonalnie)
![obraz](https://github.com/user-attachments/assets/369b962b-8db6-4ed7-b5a6-eba956414056)

**Comment by linewelder** [comment]
tak, to tak ma być (#211)

**Comment by Dzwiedzi** [comment]
Aaaa tak sorry, zapomniałem xD
