### ISSUE TITLE
[FEATURE] Zdjęcie profilowe pracownika

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#29]
Warto żeby pracownik mógł mieć zdjęcie profilowe

**Comment by linewelder** [comment]
A nie było mowy o zdjęciach profilowych dla innych użytkowników też?

**Comment by Mroxny** [comment]
> A nie było mowy o zdjęciach profilowych dla innych użytkowników też?

Tak, wszyscy po za bokiem. Nie ma tego jeszcze na diagramie ale z tego co wiem masię pojawić w najbliższej przyszłości, więc można implementować

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zdjęcia profilowe dla użytkowników](https://trello.com/c/33ItyvDx/58-zdj%C4%99cia-profilowe-dla-u%C5%BCytkownik%C3%B3w)
