### ISSUE TITLE
[BUG] GET /events zwraca 500 przy podaniu origLon, origLat

### ISSUE THREAD

**Issue by skrapi2011** [Reservant-inc/reservant-backend#294]
## Opisz błąd
GET /events zwraca 500 w przypadku podania poniższych parametrów origLat, origLon

## Do odtworzenia
Kroki do odtworzenia zachowania:
1. Wejść na Swaggera
2. Wykonać końcówkę GET /events z parametrami np:
- origLon: -122.083922
- origLat: 37.4220936

## Oczekiwane zachowanie
Zwrócenie danych

**Comment by skrapi2011** [comment]
@Mroxny Odwrotnie wartości origLon, origLat
![image](https://github.com/user-attachments/assets/d9d7a970-cfa0-4f68-b4f2-316b27fb568a)

**Comment by Mroxny** [comment]
@skrapi2011 a mógłbyś podać swój request url? Bo np u mnie działa XD
![image](https://github.com/user-attachments/assets/00b794bf-fcef-4263-9653-70a6216c828f)
