### ISSUE TITLE
[FEATURE] Potwierdzenie zrobienia zamówienia

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#304]
## Czy prośba o funkcję jest związana z problemem? Opisz go

Potrzebujemy w jakiś trywialny sposób weryfikować czy ktoś faktycznie jest w restauracji. Przy okazji potrzebujmey identyfikować gdzie siedzi dana osoba

## Opisz rozwiązanie, którego oczekujesz

Podanie numeru stolika przy którym chcemy siedzieć podczas tworzenia zamówienia. Taki numer wpisywałby użytkownik lub pracownik. Dodatkowo końcowka powinna sprawdzać czy np za godzine bedzie rezerwacja, czy ten stolik nie jest już zajęty.

**Comment by linewelder** [comment]
chodzi o confirm-start, confirm-end prawda?

jednak chcesz żeby można było ustawiać numer stolika? jest przypisywany automatycznie przy robieniu rezerwacji na razie
