### ISSUE TITLE
events

### ISSUE THREAD

**Issue by JaroslawGawrych** [Reservant-inc/reservant-backend#307]
backend nie zwraca eventow ktorymi user jest zainteresowany
backend nie zwraca listy uzytkownikow zainteresowanych eventem

**Comment by linewelder** [comment]
> backend nie zwraca eventow ktorymi user jest zainteresowany

`GET /user/events`

> backend nie zwraca listy uzytkownikow zainteresowanych eventem

`GET /events/{eventId}/interested` dla twórcy wydarzenia, było ustalono, że tylko twórca może to widzieć
