### ISSUE TITLE
Tworzenie pracownika nie przyjmuje jego imienia i nazwiska

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#32]
Wydaje mi się że podczas tworzenia pracownika serwer musi przyjmować imie i nazwisko
![image](https://github.com/Reservant-inc/reservant-backend/assets/50219282/dc66d149-710b-412c-b5f3-14a9230eb6bb)

**Comment by linewelder** [comment]
Tak, bo ta metoda tylko dodaje istniejącego pracownika do restauracji
Do stworzenia pracownika służy POST /auth/register-restaurant-employee

**Comment by linewelder** [comment]
jak mam poznaczyć to jako works as intended XD

**Comment by Mroxny** [comment]
Completed w sumie
