### ISSUE TITLE
[BUG] końcówka POST /events/:eventId/accept-user/:userId działa niepoprawnie

### ISSUE THREAD

**Issue by s24937** [Reservant-inc/reservant-backend#338]
## Opisz błąd
 Końcówka POST /events/:eventId/accept-user/:userId, dla nowo utworzonego usera zwraca, że user jest już przypisany do danego eventu. Sprawdzone dla kilku eventów. 

## Zrzuty ekranu (opcjonalnie)
<img width="958" alt="image" src="https://github.com/user-attachments/assets/d275915b-04a3-4a49-8e90-d29cbbae19f4">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/b30cbab2-f5a5-4ebc-aa6a-588f46dcd751">

**Comment by s24937** [comment]
taka sama sytuacja jest dla POST/events/:eventId/reject-user/:userId

<img width="956" alt="image" src="https://github.com/user-attachments/assets/e2ef8cb0-9adf-40bc-b2df-d96b593dd93a">
<img width="958" alt="image" src="https://github.com/user-attachments/assets/39991d6b-bc97-4c7e-99e7-954e47dea519">

**Comment by skrapi2011** [comment]
Nie udało mi się odtworzyć tego błędu

Kroki podjęte w celu próby odtworzenia:
1. Zarejestrowano klienta
2. Stworzono nowy event zaczynajacy sie w przyszlosci
3. Wyrażono chęć uczestnictwa w tym evencie jako klient
4. Jako kreator wydarzenia pomyślnie zaakceptowano klienta
5. Nastepnie jako kreator wydarzenia pomyslnie wyrzucono klienta z wydarzenia

Nie zaobserwowałem błędów w krokach 4 i 5 wspomnianych w issue
