### ISSUE TITLE
[BUG] /user/{employeeId} usuwa wszystkich pracowników JD

### ISSUE THREAD

**Issue by JaroslawGawrych** [Reservant-inc/reservant-backend#353]
![obraz](https://github.com/user-attachments/assets/a9e5d8a8-e8bc-4471-8383-ba69f2fc6dbb)

**Comment by JaroslawGawrych** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["Usuwanie" pracownika](https://trello.com/c/t0iDLg9N/141-usuwanie-pracownika)

**Comment by linewelder** [comment]
w sensie że kiedy usuwasz jednego, usuwają się wszyscy?

**Comment by skrapi2011** [comment]
> w sensie że kiedy usuwasz jednego, usuwają się wszyscy?

Podbijam pytanie

**Comment by JaroslawGawrych** [comment]
tak
