### ISSUE TITLE
[SEED] Potrzeba conajmniej 11 utworzonych eventów w JD

### ISSUE THREAD

**Issue by KubaBili001** [Reservant-inc/reservant-backend#355]

**Comment by JaroslawGawrych** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zakładka ze zgłoszeniami dotyczącymi restauracji](https://trello.com/c/nrIHOamG/139-zak%C5%82adka-ze-zg%C5%82oszeniami-dotycz%C4%85cymi-restauracji)
