### ISSUE TITLE
[BUG] Błąd końcówki POST /threads/{threadId}/add-participant 

### ISSUE THREAD

**Issue by s24937** [Reservant-inc/reservant-backend#358]
## Opisz błąd
Dla końcówki POST /threads/{threadId}/add-participant, podaję poprawne Id klienta oraz poprawne Id wątku, otrzymuję błąd 400, userId nie jest wysyłane w JSON

## Do odtworzenia

Kroki do odtworzenia zachowania:
1. Przejdź do POST /threads/{threadId}/add-participant 
2. Wprowadź threadId
3. Wyślij w body poprawne "userId"
4. Zobacz błąd

## Oczekiwane zachowanie
Odpowiedź jest 200 OK

## Zrzuty ekranu (opcjonalnie)
<img width="717" alt="image" src="https://github.com/user-attachments/assets/758587ae-29a3-45c4-ae07-b52a6b8283f2">
<img width="713" alt="image" src="https://github.com/user-attachments/assets/f6a0be06-d092-4193-811a-761b153ca38e">
<img width="715" alt="image" src="https://github.com/user-attachments/assets/e114adc8-8812-4f2c-b259-dcf756a89e85">

**Comment by linewelder** [comment]
hej, ten użytkownik nie jest customerem, tylko pracownikiem BOK, dlatego końcówka zwraca błąd
