### ISSUE TITLE
MenuItem zwraca 201 przy GET

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#37]
![image](https://github.com/Reservant-inc/reservant-backend/assets/50219282/d51598f3-0dc9-4ddf-9e00-aeed3865249d)

**Comment by Mroxny** [comment]
A właściwie to mówi że zwraca 201
![image](https://github.com/Reservant-inc/reservant-backend/assets/50219282/e8925a44-71b1-4de8-b645-c21bfc2c7dc1)

**Comment by linewelder** [comment]
Naprawiłęm to e64aad6
