### ISSUE TITLE
Brak PUT oraz DELETE dla /my-restaurants/{id}/menus oraz menu-items

### ISSUE THREAD

**Issue by Mroxny** [Reservant-inc/reservant-backend#38]

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PUT /menus/{id:int}](https://trello.com/c/qVSDE9Cy/56-put-menus-idint)

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PUT /menu-items/{id:int}](https://trello.com/c/Nene8qCh/53-put-menu-items-idint)

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Końcówki DELETE /menu/{id} i DELETE /menu-items/{id}](https://trello.com/c/rFWrxC5J/60-ko%C5%84c%C3%B3wki-delete-menu-id-i-delete-menu-items-id)
