### ISSUE TITLE
[BUG] Nie działa logowanie na stworzonego pracownika restauracji

### ISSUE THREAD

**Issue by s24937** [Reservant-inc/reservant-backend#380]
## Opisz błąd
Otrzymuję błąd logowania przy próbie zalogowania się na utworzonego pracownika restauracji

## Do odtworzenia

Kroki do odtworzenia zachowania:
1. Przejdź do swaggera
2. Spróbuj zalogować się na utworzonego przez ciebie pracownika restauracji

Oczekiwane zachowanie
Pomyślne logowanie jako pracownik restauracji 

![image](https://github.com/user-attachments/assets/c640c01d-a3f6-4a69-bd13-0f0d44785ce9)
![image](https://github.com/user-attachments/assets/57d250a9-7ba2-4630-80e7-57c79a06d329)
![image](https://github.com/user-attachments/assets/3e384cdf-cb2d-4d0f-bc69-2d3e48f604e0)
![image](https://github.com/user-attachments/assets/3a265799-9dc8-422a-b3ad-3f93b1715db5)

**Comment by linewelder** [comment]
przydałoby się więcej info, przynajmniej skriny z wywołaniami tych końcówek

**Comment by s24937** [comment]
Sorki screeny były dodane tylko chyba w komentarzu więc nie było widać, teraz już powinny być widoczne

**Comment by linewelder** [comment]
aha, już widzę, problem jest taki, że login pracowników to "login pracowdawcy+login podany przy rejestracji", czyli tu będzie JD+JanNowak. końcówka rejestracji też zwraca `"login": "JD+JanNowak"`
