### ISSUE TITLE
POST /auth/register-restaurant-employee - First name, last name zwraca 200 przy wpisaniu znaków specjalnych

### ISSUE THREAD

**Issue by AdrianSwdr** [Reservant-inc/reservant-backend#56]
Ponizszy przyklad zwraca 200 ok
{
  "login": "logintest1",
  "firstName": "!@#$%",
  "lastName": "!@#$%",
  "phoneNumber": "123456789",
  "password": "P@ssw0rd"
}

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Lepsza walidacja nazw i imion](https://trello.com/c/QmaMoruh/130-fix-lepsza-walidacja-nazw-i-imion)
