### ISSUE TITLE
POST /auth/register-customer-support-agent / POST /auth/register-customer -  zwraca 200 dla każdego użytkownika + imię nazwisko znaki specjalne

### ISSUE THREAD

**Issue by AdrianSwdr** [Reservant-inc/reservant-backend#57]
200 Niezalogowany 
200 Customer
200 Restaur Owner 
200 support@mail.com 
200 manager@mail.com 
200 JD+hall 
200 JD+backdoors  
200 JD+employee  
200 Imie nazwisko znaki specjalne

**Comment by linewelder** [comment]
chodzi o to że niezalogowani użytkownicy mogą z nich korzystać?

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Lepsza walidacja nazw i imion](https://trello.com/c/QmaMoruh/130-fix-lepsza-walidacja-nazw-i-imion)
