### ISSUE TITLE
GET /auth/is-unique-login - Zwraca 200 dla loginu '!@#$%'

### ISSUE THREAD

**Issue by AdrianSwdr** [Reservant-inc/reservant-backend#58]

**Comment by linewelder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FIX] Lepsza walidacja nazw i imion](https://trello.com/c/QmaMoruh/130-fix-lepsza-walidacja-nazw-i-imion)

**Comment by linewelder** [comment]
Postanowiliśmy, że ta końcówka nie będzie sprawdzać prawidłowości loginu, napiszemy to w Swaggerze
