### ISSUE TITLE
Menu POST/menus

### ISSUE THREAD

**Issue by s24937** [Reservant-inc/reservant-backend#77]
<img width="716" alt="Menu_POST_:menus_14 05" src="https://github.com/Reservant-inc/reservant-backend/assets/127143262/5516ab18-b81b-426e-868a-2488b7f4e9cd">

Id zmieniło się automatycznie z 2 na 5 (analogicznie wcześniej z 1 na 4), gdy nie wstawiam żadnego ID to nie mogę wysłać requesta, "alternateName" jest ustawiony domyślnie na null (pytanie czy tak ma być)

**Comment by linewelder** [comment]
Zwracane ID różni się od podanego dlatego, że podajemy ID restauracji, a dostajemy ID stworzonego menu. W najbliższym czasie sprecyzujemy wszystkie ID (np. `id` -> `menuId`), więc będzie od razu widać.

ID musi być wysyłane dlatego, że menu powinno być podłączone do restauracji.

Tak, `alternateName` ma być domyślnie ustawiane na `null`.
