### ISSUE TITLE
alternate name w menu jest required

### ISSUE THREAD

**Issue by Bambi54** [Reservant-inc/reservant-backend#89]
wysłałem request na końcówkę: http://172.21.40.127:12038/menus z danymi:
{"id":null,"name":"aa","restaurantId":1,"alternateName":"","menuType":"Food","dateFrom":"2024-05-19","dateUntil":"2024-05-21","menuItems":null}

i dostałem zwrotkę:
{"status":400,"errors":{"alternateName":["The AlternateName field is required."]}}

chyba alternate name powinno być optional?

**Comment by linewelder** [comment]
Dlatego że jeśli nie chcesz jego ustawiasz musisz podać nulla. Natomiast myślę, że musimy w takim wypadku pisać "cannot be null" zamiast "is required", żeby było mniej mylące

**Comment by Bambi54** [comment]
ok, racja, już działa :))
